apiVersion: v1
kind: Endpoints
metadata:
  # Name must match service name
  name: custom-external-node-exporter-svc
  namespace: test-cluster
  labels:
    app: custom-external-node-exporter-svc
subsets:
  - addresses:
    - ip: 172.29.55.41
    ports:
      - name: https
        port: 9105
        protocol: TCP
