apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: kube-logging
data:
  fluent.conf: |
    <source>
      @type tail
      format json
      read_from_head true
      tag file-myapp.log
      path /app/example-log.log
      pos_file /tmp/example-log.log.pos
    </source>

    <filter file-myapp.log>
      @type record_transformer
      <record>
         host_param "#{Socket.gethostname}"
      </record>
    </filter>

    <match file-myapp.log>
       @type stdout
    </match>

