---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spike-tenant-namespace-user
  namespace: spike-tenant-namespace

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: spike-tenant-namespace-user-full-access
  namespace: spike-tenant-namespace
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: spike-tenant-namespace-user-view
  namespace: spike-tenant-namespace
subjects:
- kind: ServiceAccount
  name: spike-tenant-namespace-user
  namespace: spike-tenant-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spike-tenant-namespace-user-full-access

