apiVersion: v1
kind: Service
metadata:
  name: rpc-app-service
  labels:
    app: rpc-app
  namespace: custom-ns
spec:
  type: LoadBalancer
  ports:
  - name: web
    port: 8081
    targetPort: 8081
  selector:
    app: rpc-app
