apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: node-exporter
    app.kubernetes.io/version: v0.18.1
  name: node-exporter
  namespace: custom-ns
spec:
  type: LoadBalancer
  ports:
  - name: https
    port: 9105
    targetPort: https
  selector:
    app.kubernetes.io/name: node-exporter
