apiVersion: v1
kind: Endpoints
metadata:
  # Name must match service name
  name: custom-external-svc
  namespace: test-cluster
  labels:
    app: custom-external-svc
subsets:
  - addresses:
    - ip: 172.29.55.41
    ports:
      - name: metrics
        port: 8185
        protocol: TCP
