apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: custom-external-apps
  name: custom-external-svc
  namespace: test-cluster
spec:
  endpoints:
  - interval: 30s
    port: metrics
  selector:
    matchLabels:
      app: custom-external-svc

