apiVersion: v1
kind: Endpoints
metadata:
  # Name must match service name
  name: custom-external-rpc-svc
  namespace: test-cluster
  labels:
    app: custom-external-rpc-svc
subsets:
  - addresses:
    - ip: 172.29.55.41
    ports:
      - name: web
        port: 8081
        protocol: TCP
