---
apiVersion: v1
kind: Pod
metadata:
  name: sample-mw-app
  namespace: custom-ns
  annotations:
    vault.hashicorp.com/agent-inject: 'true'
    vault.hashicorp.com/role: 'injectedmwapp'
    vault.hashicorp.com/agent-inject-secret-config.txt: 'kv/prod/mwapps/mw-server-controllers'      
spec:
  tolerations:
  - key: location
    effect: NoSchedule
    operator: Equal
    value: gc
  containers:
  - image: nginx:latest
    name: nginx
  serviceAccountName: mw-vault-auth
